spring.application.name=SpringSecDemo
server.port=5678
#spring.security.user.name=akash
#spring.security.user.password=123
server.servlet.session.cookie.same-site=strict
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringJDBC
spring.datasource.username=postgres
spring.datasource.password=Fkp37Si@n
spring.datasource.driver-class-name=org.postgresql.Driver